### ISSUE TITLE
this is not nightwatch api in step definition functions.

### ISSUE THREAD

**Issue by airtonix** [mucsi96/nightwatch-cucumber#129]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**

```json
    "cucumber": "^1.3.1",
    "nightwatch": "^0.9.6",
    "nightwatch-cucumber": "^5.5.2",
```

```js
// client/tests/e2e/steps/index.js
var debug = require('debug')('test/e2e/steps');

module.exports = function () {
	debug('loading');
	require('../parts/general').call(this, options);
	debug('ready');
};
```

```js
// client/tests/e2e/parts/general.js
/*eslint no-param-reassign: "options" */
var debug = require('debug')('test/e2e/parts/general');

module.exports = function (options) {
	debug('loading');

	options = Object.assign({}, options);

	/**
	 * Assert something displays the text
	 * @param  {any} selector   xPath selector
	 * @param  {String} text  text to confirm
	 */
	this.Then('"$selector" should display "$text"',
		function assertTextIsDisplayed (selector, text, done) {
			debug('Then.assertTextIsDisplayed', selector);
			this.useXpath()
				getText(selector, function (result) {
					this.assert.equal(typeof result, 'object');
					this.assert.equal(result.status, 0);
					this.assert.equal(result.value, text);
					done();
				});
	});
}
```

```bash
...
   Step Definition: client/test/e2e/parts/general.js:16
   Message:
     TypeError: this.useXpath is not a function
...
```

**Expected/desired behavior**

That `this` inside a step definition be the nightwatch api.

**Comment by airtonix** [comment]
Seems that when a step definition has a callback as the last argument, then the nightwatch api is not available inside the step definition.

**Comment by mucsi96** [comment]
Hi @airtonix! Thanks for your feedback! Can we discuss this topic on [gitter](https://gitter.im/mucsi96/nightwatch-cucumber) ?

**Comment by mucsi96** [comment]
I think this behavior is correct and it is documented. There is no point to use callback and Nightwatch API together, because Nightwatch is based on lazy execution. Nightwatch instead of executing webdriver commands in command execution time is building an async tree of tasks to be done later. On the other hand executing the callback tells Cucumber.js that the step was executed and we can got to the next step. But Nightwatch does not execute its whole async tree at that time. That's why the step definition callback is executed inside the `nightwatch-cucumber` framework after Nightwatch is done with all tasks in the async tree. I hope this helps

**Comment by airtonix** [comment]
I beg to differ.

Without the callback, subsequent steps begin to execute before the current step has finished, this causing failure of my tests.

I had to roll back to an older version of your library.

**Comment by airtonix** [comment]
I mean what's the point of a step definition that can't make use of the nightwatch api?

**Comment by mucsi96** [comment]
@airtonix Can you provide an example app which has a problem because of that. Nobody is complaining about that. Let's for example check the usage in Nightwatch docs for `getTitle` function http://nightwatchjs.org/api/getTitle.html
```
this.demoTest = function (browser) {
   browser.getTitle(function(title) {
     this.assert.equal(typeof title, 'string');
     this.assert.equal(title, 'Nightwatch.js');
   });
 };
```
It does not contain any external callback. 

Also the point of having a step_definition without nighwatch api is for example a given step which can do some asynchronous setup. For example add some data to db.

**Comment by mucsi96** [comment]
You should not fix asynchronous code using (callback, promise or generator) with a totally different world of nightwatch async tree where the code looks like it is synchronize.  But I need to check the support of generators with `nightwatch-cucumber` as generators are supported by cucumber.js out of the box

**Comment by esteban-uo** [comment]
Hi @mucsi96 ! first I want to thank you for creating this bridge with cucumber!

I agree with @airtonix, I think there are different use cases where async calls make sense between steps or even scenarios. Nightwatch provide an API in order to achieve it https://github.com/nightwatchjs/nightwatch/blob/master/examples/unittests/testUtils.js so if they provided, they were aware of this . For instance I have step 1 and I need to call a database and create a record, I need it before going to step 2.

**Comment by mucsi96** [comment]
Hi @esteban-uo! Thanks for your feedback! Please notice that there is no callback parameter for `testMakeFnAsync ` function. Every test case gets only the `client`. And client is handling async executions internally. Please provide a minimal example with the problem. I will help to solve it :)

**Comment by esteban-uo** [comment]
thanks @mucsi96! a simple example could be:

```js
  this.Given(/^a user "([^"]*)"$/, function (name) {
    fetch('http://another/api', {
      method: 'POST'
      body: { name },
    });
  });

  this.Then(/^user "([^"]*)"$ can see dashboard$/, function (name) {
    const userDashboard = this.page.userDashboard();
    userDashboard.navigate(userDashboard.url(name))
      .waitForElementVisible('@page', 1000);
  });
```

I need step 1 to wait to be done, so to step 2 can be fulfilled.

**Comment by mucsi96** [comment]
You can return promise in step definition. And it will async
```
this.Given(/^a user "([^"]*)"$/, function (name) {
    return fetch('http://another/api', {
      method: 'POST'
      body: { name },
    });
  });
```

Or you can you generators
```
this.Given(/^a user "([^"]*)"$/, function * (name) {
    yield fetch('http://another/api', {
      method: 'POST'
      body: { name },
    });
  });
```
Hope this helps. I will close the separately ceated issue #146
