### ISSUE TITLE
BeforeFeature handler is not being called

### ISSUE THREAD

**Issue by eamonnfaherty** [mucsi96/nightwatch-cucumber#206]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
```

**Current behavior**
within my global path and within my hooks the following is not being called before a feature:

const {defineSupportCode} = require('cucumber')

defineSupportCode(({registerHandler}) => {
    registerHandler('BeforeFeature', function (feature, callback) {
        //TODO : have this called!
        callback();
    });
});

**Expected/desired behavior**
the function should be called

**Please tell us about your environment:**

* **nightwatch-cucumber version:** 7.1.0

* **nightwatch version:** 0.9.14

* **cucumber version:** 2.0.0-rc.9

* **Node.js version:** 7

**Comment by mucsi96** [comment]
Hi @eamonnfaherty! Thanks for you feedback! Can you compare this example with your code? https://github.com/mucsi96/nightwatch-cucumber/tree/master/examples/event-handlers-with-callback-example I think that the problem is in your code. Because I have a green test for this case. Are you sure that this file is included?
