### ISSUE TITLE
While running via groups, the tests(.js files) in different folders also getting copied to temp_test folder

### ISSUE THREAD

**Issue by sanmaru** [mucsi96/nightwatch-cucumber#23]
Hi 
I have been using the groups feature. So while running the scripts via groups i noticed something different, though it won't effect the execution but the framework copies the tests from different folder to temp-test folder.

I have attached the screenshot for your reference.
![nightwatch-cucumber_issue](https://cloud.githubusercontent.com/assets/8145154/12374761/164bf018-bc5b-11e5-801e-ce43164e17c6.png)

**Comment by mucsi96** [comment]
Hi
Thanks for you feedback!

Hoverer this is the expected behavior. 

The module first runs cucumber with all feature files and create dummy nightwatch tests. We can't get nightwatch command line arguments at this stage :(

In the second stage nightwatch runs the created dummy test files as normal nightwatch test files. At this stage we can use all nightwatch CLI features.

**Comment by mucsi96** [comment]
I released a new version which does not create `temp-tests` folder. Check the readme, because configurations is little different and simpler :)
