### ISSUE TITLE
Feature execution Reporting

### ISSUE THREAD

**Issue by sharathkonda** [mucsi96/nightwatch-cucumber#35]
Is it possible to generate a report similar to Cucumber-jvm for scenario/feature report indicating pass, failure etc.

My CI displays well but when I run with the cucumber runner with the command node nightwatch.js --tag test
It doesn't display.

**Comment by mucsi96** [comment]
If you need Cucumber JSON output (I think this is the Cucumber-jvms output) you need to use this plugin in Cucumber.js as runner mode. To set the proper formatter check out the [Cucumber.js readme](https://github.com/cucumber/cucumber-js#formatters). But the problem is that Cucumber.js as runner mode is still work in progress.

**Comment by mucsi96** [comment]
I released a new `1.4.0` version which contains more stable Cucumber.js as runner mode. You can try to get Cucumber JSON output. Good luck with that! :)
