### ISSUE TITLE
Mink support

### ISSUE THREAD

**Issue by pebie** [mucsi96/nightwatch-cucumber#47]
Hi,

This stack was amazing thanks :)

Because [cucumber-mink](http://cucumber-mink.js.org/) propose many usefull step, did you plan a support for cucumber-mink at the top of cucumberJS ?

**Comment by mucsi96** [comment]
Hi! I don't really understand what is this feature request about, because cucumber-mink is an integration project between cucumberJs and webdriverio. This projects is similar, but is using NightwatchJs. Also I think there is no point to have pre defined helper steps as in BDD the steps should be in business domain language not in browser language. Predefined helper steps are training wheels which helps to use Cucumber badly http://aslakhellesoy.com/post/11055981222/the-training-wheels-came-off

I am closing this issue as it won't be fixed

**Comment by pebie** [comment]
Thanks for your time.
My point was just to propose what mink d. But you're right, steps should be in business domain even if common task propose by Mink are great.
