### ISSUE TITLE
Ability to use arrow functions.

### ISSUE THREAD

**Issue by Cmdv** [mucsi96/nightwatch-cucumber#82]
I know due to the current lexical scope, `this` is passed through the function but it would really nice to be able to use arrow functions eg:

```
module.exports = () =>
  this.Given(/^I open Google's search page$/, () =>
    this
      .url('https://www.google.co.uk')
      .waitForElementVisible('body', 1000)
  )
```

Is there a way to do this or is the best way to just keep using `function`?

**Comment by mucsi96** [comment]
Hello  @Cmdv! Thanks for feedback! You can't use this in arrow function as no matter how hard I try to .bind the method to a specific context, it will not change. The ES6 arrow function syntax will always override any previously bound or dynamically determined value of “this”. The only solution is to pass the value of this as argument. But this is only possible with the inner function. As outer functions is called by Cucumber.js. I think that solution would be not ideal because of inconsistency

**Comment by Cmdv** [comment]
Hi @mucsi96 yes I see what you mean after checking out source code, good ol lexical scope haha well not to worry it's not the end of the world I don't mind using the word `function` keeping with my routes 😋 

I'll close the issue, and thanks for prompt reply

**Comment by mucsi96** [comment]
Hi @Cmdv! Arrow function are supported now! https://github.com/mucsi96/nightwatch-cucumber#nightwatch-client-as-parameter

**Comment by Cmdv** [comment]
@mucsi96 superb, thanks for letting me know
