### ISSUE TITLE
Running more than 3 feature file doesn't work

### ISSUE THREAD

**Issue by jdariva** [mucsi96/nightwatch-cucumber#93]
I'm working with more than 3 feature files using nightwach as runner.

When I run the tests only execute 3 feature files: the first one, the second one and the last one. I can't see why didn't run the other tests. In the logs there are no errors.

/test $ ls -l features/
total 40
-rw-r--r-- 1 jacobo jacobo 5963 sep 14 10:57 CasoUso01.feature
-rw-r--r-- 1 jacobo jacobo 5397 sep 14 12:59 CasoUso02.feature
-rw-r--r-- 1 jacobo jacobo 7065 sep 14 17:33 CasoUso03.feature
-rw-r--r-- 1 jacobo jacobo 2499 sep 14 17:30 CasoUso04.feature
-rw-r--r-- 1 jacobo jacobo  280 sep 15 08:48 CasoUso05.feature
drwxr-xr-x 2 jacobo jacobo 4096 sep 14 14:29 step_definitions

If I delete the files CasoUso04.feature and CasoUso05.feature nightwatch runs propertly CasoUso03.feature

**Please tell us about your environment:**

* **nightwatch-cucumber version:** 4.1.0

* **nightwatch version:** 0.9.6

* **cucumber version:** 1.2.1

* **Node.js version:** 0.12.15

**Comment by jdariva** [comment]
Sorry, the problem was an error. I forget to write something in the Feature definition.

**Comment by mucsi96** [comment]
Thank you for the feedback. I am working on a new runner on the dev branch. I would like to improve the error handling there

Sent from Yahoo Mail on Android 
 
  On Thu, Sep 15, 2016 at 9:51, jdariva<notifications@github.com> wrote:   
Sorry, the problem was an error. I forget to write something in the Feature definition.
